### ISSUE TITLE
Create learning Card grid

### ISSUE THREAD

**Issue by czintel** [czintel/capstone-project#1]
## Value statement - a requirement, not a solution
As a **user** 
I want to **have a list of cards each containing information about one of the basic emotions** 
so that **I can learn about them**

## Description (Text, Scribble, Wireframe, Design)
![Bildschirmfoto 2021-06-02 um 21 53 38 Kopie](https://user-images.githubusercontent.com/80048997/120647400-db588d80-c47a-11eb-9425-6d19c0987310.jpg)
![Bildschirmfoto 2021-06-02 um 21 53 38 Kopie_02](https://user-images.githubusercontent.com/80048997/120647413-e01d4180-c47a-11eb-9cae-db664330d06d.jpg)

## Acceptance criteria
- [x] LearningCard should contain information about one basic emotion
- [x] LearningCard should consist of title, paragraph, tags and a hide & show button
- [x] Click on button hides all information (title never hidden)
- [x] LearningCard should be displayed in a grid
- [x] LearningCardPage contains a button that takes you QuizCardPage (logic follows at a later stage)

## Tasks
- [x] Create feature branch
- [x] Create LearningCard component
- [x] Add basic styling to LearningCard component
- [x] Add logic
- [x] Create test for LearningCard component
- [x] Create card page with list of cards
- [x] Add basic styling for LearningCardPage

## Complexity (low, medium, high)
medium
