### ISSUE TITLE
create navigation bar

### ISSUE THREAD

**Issue by czintel** [czintel/capstone-project#16]
## Value statement
As a **user** 
I need **a navigation bar** 
so that **I can switch between different pages** 

## Description (Text, Scribble, Wireframe, Design)
<img width="785" alt="Bildschirmfoto 2021-06-18 um 12 11 30" src="https://user-images.githubusercontent.com/80048997/122545651-5babf080-d02e-11eb-9579-c5098b927bb1.png">

## Acceptance criteria
- [x] NavBar created using react-router
- [x] NavBar must be fixed at the bottom
- [x] NavBar lays above all other elements
- [x] Click on page button leads you to said page
- [x] Click on page button sets page button active

## Tasks
- [x] Create feature branch
- [x] Create footer in App.js
- [x] Create Nav Bar component
- [x] Place Nav Bar component in footer
- [x] Test functionality
- [x] Add stlying and fix placement in App

## Complexity (low, medium, high)
low
