### ISSUE TITLE
Form asking for user name

### ISSUE THREAD

**Issue by czintel** [czintel/capstone-project#2]
## Value statement - a requirement, not a solution
As a **user** 
I need **to type and submit a name into the form** 
so that **I can enjoy a personalized user experience** 

## Description (Text, Scribble, Wireframe, Design)
![Bildschirmfoto 2021-06-03 um 14 42 24_02](https://user-images.githubusercontent.com/80048997/120652538-2628d400-c480-11eb-86cf-8ebe656d3822.jpg)

## Acceptance criteria
- [ ] Name submit must be required
- [ ] String must not be empty
- [ ] First letter of the Name should automatically be turned into uppercase
- [ ] Name is saved into localStorage
- [ ] Click on "Los geht's" saves name of user
- [ ] Click on "Los geht's" takes you to the learning section and shows a personalized introduction page

## Tasks
- [ ] Create feature branch
- [ ] Create form
- [ ] Add logic
- [ ] Use localStorage
- [ ] Create test

## Complexity (low, medium, high)
medium
