### ISSUE TITLE
Create quiz card

### ISSUE THREAD

**Issue by czintel** [czintel/capstone-project#3]
## Value statement - a requirement, not a solution
As a **user** 
I want to **see a quiz card confronting me with a fictitious scenario** 
so that **I can answer how I interpret the situation** 

## Description (Text, Scribble, Wireframe, Design)
<img width="292" alt="Bildschirmfoto 2021-06-02 um 22 19 57" src="https://user-images.githubusercontent.com/80048997/120548097-40b46c00-c3f2-11eb-9743-37231d844064.png">

## Acceptance criteria
- [ ] Quiz card must contain title,indicator icon, paragraph, question, answer tags and a submit button
- [ ] Answer tags must be clickable
- [ ] Wrong answer tags turn red when clicked
- [ ] Correct answer tags turn green when clicked
- [ ] Correct submission reveals an explanatory text
- [ ] Correct submission toggles indicator icon
- [ ] Correctly answered cards get hidden and moved to section "quiz-cards-correct"

## Tasks
- [ ] Create feature branch
- [ ] Create component
- [ ] Add logic
- [ ] Add basic styling
- [ ] Create test

## Complexity (low, medium, high)
medium
