### ISSUE TITLE
Quiz card filter function

### ISSUE THREAD

**Issue by czintel** [czintel/capstone-project#4]
## Value statement - a requirement, not a solution
As a **user** 
I want **to be able to filter between answered and to be answered quiz cards** 
so that **I can toggle correctly answered quiz cards** 

## Description (Text, Scribble, Wireframe, Design)
![120650666-4d7ea180-c47e-11eb-8b78-4643f143744f](https://user-images.githubusercontent.com/80048997/123648262-1905c780-d829-11eb-9a73-db2623176f39.jpg)

## Acceptance criteria
- [x] Filter icon on of the quiz page toggles between "correctly answered" / "still to be answered" and "show all cards"
- [x] "Lernen" button takes you back to the learning section
- [x] Quiz cards should be displayed in a grid layout

## Tasks
- [x] Create branch
- [x] Add filter logic / useState

## Complexity (low, medium, high)
medium
