### ISSUE TITLE
Create form asking for user name

### ISSUE THREAD

**Issue by czintel** [czintel/capstone-project#6]
## Value statement - a requirement, not a solution
As a **user** 
I need **to type and submit a name into the form** 
so that **I can enjoy a personalized user experience** 

## Description (Text, Scribble, Wireframe, Design)
![Bildschirmfoto 2021-06-03 um 14 42 24_02](https://user-images.githubusercontent.com/80048997/120652538-2628d400-c480-11eb-86cf-8ebe656d3822.jpg)

## Acceptance criteria
- [x] Name is saved into localStorage
- [x] Click on "Los geht's" saves name of user
- [x] Click on "Los geht's" takes you to the learning section and shows a personalized introduction page

## Tasks
- [x] Create feature branch
- [x] Create form
- [x] Add logic
- [x] Use localStorage
- [x] Create test

## Complexity (low, medium, high)
medium
